language: python
python:
- 3.6
install:
- pip install -U tox-travis
- pip install poetry
script: tox
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: pwoolvett
  password:
    secure: BtJGI45HUsG68f6UOAVX4yAqcEdgVfo9kF/bwHlLQSQYu7sJxb+dPRelheaYeEIbqPHGG7UyQlo1CjtJDLtAj1fs32WVHYMv+CuVehs9gjJC6uaz4mNhjG0RWdjMEvq9jATd77IXuVHPl19wIyUz8Ryq93BCqMcKSc/hkuuUZ+l7nhRARpubX2v6h4kbgfwAHwyQ0vSXTWvLvGdBu9M9JzpI0JLlzyhIaL8M3hB6LwlG2SJ2H/VHRXlNxuhGyAega+RC8o6ObeyKJ42Xw98aCji4G9aFVUgXaJuOmxktBuTqjdAsGy8IANQ5G0TKBmnPs8Une9QtYg2g1/exNpgC1lR0/EYvcBaU1MI60XmV+1r0+GliH+zMAJWqeoKjO52ZdEqK1KNR8pUsGQDTvCMiCZ04i7gDFnfBQvSGwHFuW+eX4qrcuhD8u8MpAhgFEvT0AXzb4H7Vz/jK2cchV8J96uQ/4z+qxfM7X2RtagpnNfZzbbi33HBsTt44T+w4FpODqScQuGmKGbfso3oJZqcNTT9YvBrwuBD0QPdRl/JWgm8GxyuuQOlvAXcuJgE/z29xBtEc54GLG8QhfrD/9kIiXdj0B2XB97mdrtxw+lmEl37hPHgtsmGjbb1tUhHRgTSP0dFI64WvIQzQhqTAEkmKeBtMvQjHpZfSgyWimvh1VrA=
  on:
    branch: master
    repo: pwoolvett/petri
    python: 3.6
