language: python
cache: pip
python:
- 3.6
env:
  global:
  - secure: iwuIb20/aC2tmLoGJO9WlMzirqkRPnb0+b8NFEjnFjKdBjtTCNiMmLGIDcMq/7ohiObJmDqZk+ubg5aKejaGmWrjHWQLP2cFi56bi0czEH6PUmDW44/6jyvQqR634cOH0IbeGHpwcm+N+iZkmgQLCXAs1L4iyLHyn20ljSUI/ncHhOWWUaLdt6DJ95zKou5zDtcStgPLMi3oYTa7I4ZBf/6M25Q9klnT/DaBxuGmWCm4eOuORuq667Zpt2U2Smg1UebGafVPSf2ZdgPw5wVqvxAy1mrvMuQav0MMwD17GgE92NxYrZ82haVFZEU19NT8wFV+ycwClepvHAXKcF7YZKdawhW/FYvKS1mkeG1Ois3St6kmLaa0+3AudU15Oq379qlGzOfP+5rpf4LgzICCWp6R8wkRti8U1xE+pTb713nwxoqxjdWJEd5CL/mpjQ+nm+vJ0vmTlJFqWkLxgZB8yCUpkBDAhCnKuCzSeyPID+n4tl/VmEvK+alJ/wL5XMK9hX+uncoPWgu5e4tuB8wgOzp4m793R4b5UGiuAvJnE90s0drguHQlOuDw8LKLmgY3xUayuTuG2sBTbQtgen8G7MFyjSyka7Rd1SC0SlT+ZjHsBm3w6gEg5+zVQzm0ukLftGqIQDUv0TL4O/oOTsZVwUfFZn+2IaN8leVZQ6XbZ8M=
  - secure: DvilJ52NjacE3bZoUU39YxVaZbiogI8VfEmm35sc2BU06pS+FAiqNVf+LLepOj39H3vYwafW5T0dqhunOyg+dRcQn+bWXWHP6HEPIcBQr9rvhyjTGTF4NHkAjxDhOKVul8+JYYsw+YLGOLcjzqgdnL16IxGfH1v6ZDt1RKMh7xssLJFfonEhjJJ1vqRqddWZsM6ty95bi7FeBEIPOCPV16iwwdUCMhHAAc22+Ci64+OcWWEhU9F6snecZZcrJU+JarrI012ZXBw4sVTqAnrra+KKdutapg7JCTKSOADNyNghW1ubp3mlCnE9bvXmcWmozkXqs2NbKg2BumznPpKOlb1/Vyn65FAnP/Ugm+XPhkUl2nJd1/NsqIGrssb4HHw9Hj0eoG08+t6E8AwG/BAB7eB/8OYd/bDWbZBL8jwyrELEYu8ORXysJuzfFlDw0B4y9ROkEwLZv9GEIHK3XqFtCPqBGicx7Iyy0v8BOBabYgukqEHuot5ij7MqMJXxkmOwYGrj4PRsVsnp9I/ePdunEHQIeWtXYJ2bNAhSbk6zCSgdoTrglonEhstO9vRMfCjLOhfeM6mO9106kZ6UvNhhK870C9qSizoOG+MNDE8Kch2hjY/rWXlil23xektnJ94JusPkuCpZNIh38ysrE96FKdX/T5/Ybt1i27UfBqLsGw4=
before_install:
- pip install poetry
- pip install -U tox-travis
install:
- poetry install
script:
- tox
before_deploy:
- poetry config repositories.pypi https://upload.pypi.org/legacy/
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
- poetry build
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: script
  script: poetry publish -r pypi
  on:
    branch: master
    repo: pwoolvett/petri
    python: 3.6
