version: "3.7"
services:

  petri:
    depends_on:
      - notpypi
    build: .
    entrypoint:
      - sleep
      - infinity

  a_pkg:
    depends_on:
      - notpypi
    build:
      context: ./tests/a_pkg
      dockerfile: Dockerfile
      args:
        - PYPI_USERNAME=${PYPI_USERNAME}
        - PYPI_PASSWORD=${PYPI_PASSWORD}
    environment:
      - PYPI_USERNAME
      - PYPI_PASSWORD

  second_order:
    build:
      context: ./tests/second_order
      dockerfile: Dockerfile
      args:
        - PYPI_USERNAME=${PYPI_USERNAME}
        - PYPI_PASSWORD=${PYPI_PASSWORD}
    environment:
      - PYPI_USERNAME
      - PYPI_PASSWORD

  notpypi:
    image: praekeltfoundation/pypiserver
    ports:
      - "8080:8080"
    volumes:
      - ./docker/.htpasswd:/.htpasswd
    #   - ./packages:/packages
