
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='petri',
    version='0.23.1',
    description='Free your python code from 12-factor boilerplate.',
    python_requires='==3.*,>=3.6.0',
    project_urls={'homepage': 'https://pypi.org/project/petri/', 'repository': 'https://github.com/pwoolvett/petri', 'documentation': 'https://petri.readthedocs.io/en/stable/'},
    author='Pablo Woolvett',
    author_email='pablowoolvett@gmail.com',
    license='Unlicense',
    keywords='pyproject.toml dotenv boilerplate 12-factor pydantic log',
    packages=['petri'],
    package_data={},
    install_requires=['importlib-metadata==0.*,>=0.23.0', 'pydantic==0.*,>=0.32.2', 'python-dotenv==0.*,>=0.10.3', 'structlog==19.*,>=19.1.0'],
    extras_require={'dev': ['autopep8==1.*,>=1.4.4', 'bandit==1.*,>=1.6.2', 'blackini==0.*,>=0.1.6', 'doc8==0.*,>=0.8.0', 'docformatter==1.*,>=1.3.0', 'docutils==0.*,>=0.15.2', 'flake8==3.*,>=3.7.8', 'flake8-bugbear==19.*,>=19.8.0', 'isort==4.*,>=4.3.21', 'mypy==0.*,>=0.720.0', 'pip==19.*,>=19.2.3', 'pylint==2.*,>=2.4.1', 'pytest==5.*,>=5.1.2', 'pytest-cov==2.*,>=2.7.1', 'pytest-html==2.*,>=2.0.0', 'sphinx==1.*,>=1.8.0', 'sphinx-autodoc-typehints==1.*,>=1.5.0', 'sphinx-rtd-theme==0.*,>=0.4.2', 'sphinxcontrib-apidoc==0.*,>=0.3.0'], 'lint': ['bandit==1.*,>=1.6.2', 'flake8==3.*,>=3.7.8', 'flake8-bugbear==19.*,>=19.8.0', 'mypy==0.*,>=0.720.0', 'pylint==2.*,>=2.4.1'], 'color': ['colorama==0.*,>=0.4.1'], 'docs': ['doc8==0.*,>=0.8.0', 'docutils==0.*,>=0.15.2', 'sphinx==1.*,>=1.8.0', 'sphinx-autodoc-typehints==1.*,>=1.5.0', 'sphinx-rtd-theme==0.*,>=0.4.2', 'sphinxcontrib-apidoc==0.*,>=0.3.0'], 'pytest': ['pytest==5.*,>=5.1.2', 'pytest-cov==2.*,>=2.7.1', 'pytest-html==2.*,>=2.0.0']},
)
