
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='petri',
    version='0.22.2',
    description='Handle project/application config from pyproject.toml',
    python_requires='==3.*,>=3.6.0',
    author='Pablo Woolvett',
    author_email='pablowoolvett@gmail.com',
    entry_points={'console_scripts': ['petri = petri.__main__:_main']},
    packages=['petri'],
    package_data={},
    install_requires=['autologging==1.*,>=1.3.0', 'logzero==1.*,>=1.5.0', 'pydantic==0.*,>=0.32.2', 'python-dotenv==0.*,>=0.10.0', 'toml==0.*,>=0.10.0', 'tzlocal==1.*,>=1.5.0'],
    extras_require={'dev': ['autopep8==1.*,>=1.4.0', 'bandit==1.*,>=1.6.0', 'behave==1.*,>=1.2.0', 'black', 'coverage==4.*,>=4.5.0', 'doc8==0.*,>=0.8.0', 'docformatter==1.*,>=1.1.0', 'flake8==3.*,>=3.7.0', 'flake8-bugbear==19.*,>=19.3.0', 'hypothesis==4.*,>=4.17.0', 'mypy==0.*,>=0.701.0', 'mypy-extensions==0.*,>=0.4.0', 'pep8==1.*,>=1.7.0', 'pylint==2.*,>=2.3.0', 'pytest==4.*,>=4.0.0', 'pytest-cov==2.*,>=2.6.0', 'sphinx==1.*,>=1.8.0', 'sphinx-autobuild==0.*,>=0.7.1', 'sphinx-autodoc-typehints==1.*,>=1.5.0', 'sphinx-rtd-theme==0.*,>=0.4.2', 'sphinxcontrib-apidoc==0.*,>=0.3.0'], 'tqdm': ['tqdm==4.*,>=4.36.1']},
)
