version: "3.7"
services:
  publisher:
    depends_on:
      - notpypi
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - NOT_PYPI_USERNAME=${NOT_PYPI_USERNAME}
      - NOT_PYPI_PASSWORD=${NOT_PYPI_PASSWORD}
    volumes:
      - ./.coverage.publish:/petri/.coverage

  a_pkg:
    depends_on:
      - notpypi
    build:
      context: ../tests/a_pkg
      dockerfile: Dockerfile
    environment:
      - NOT_PYPI_USERNAME=${NOT_PYPI_USERNAME}
      - NOT_PYPI_PASSWORD=${NOT_PYPI_PASSWORD}
      - PETRI_VERSION=${PETRI_VERSION}
    volumes:
      - ./.coverage.pkg:/petri/.coverage

  second_order:
    depends_on:
      - notpypi
    build:
      context: ../tests/second_order
      dockerfile: Dockerfile
    environment:
      - NOT_PYPI_USERNAME=${NOT_PYPI_USERNAME}
      - NOT_PYPI_PASSWORD=${NOT_PYPI_PASSWORD}
    volumes:
      - ./.coverage.second_hand:/petri/.coverage

  notpypi:
    image: praekeltfoundation/pypiserver
    ports:
      - "8080:8080"
    volumes:
      - ./.htpasswd:/.htpasswd
