[tool.poetry]
name = "a_pkg"
version = "1.2.3"
description = "A description"
authors = ["Author Name <author@mail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
